application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script:app.app

- url: /mysql
  script: app_mysql.app

libraries:
- name: MySQLdb
  version: "latest"
